name: Firebase Trigger
description: Update a field in your firebase database
author: Jeremy Shore
inputs:
  credentials:
    description: Admin credentials json for connecting to application
    required: true
  databaseUrl:
    description: URL to the database you want to connect to
    required: true
  databaseType:
    description: Either `realtime` or `firestore`
    default: realtime
  path:
    description: Path to what you want to set in your database
    required: true
  doc:
    description: Document to set for firestore
  value:
    description: Value to be set
runs:
  using: node12
  main: dist/index.js